### ISSUE TITLE
Failed to resolve: com.github.ixiDev:GDPRChecker:v0.1

### ISSUE THREAD

**Issue by DjarallahBrahim** [ixiDev/GDPRChecker#1]
Hi
when i put this  implementation 'com.github.ixiDev:GDPRChecker:v0.1'
in my gradle it gives me : Failed to resolve: com.github.ixiDev:GDPRChecker:v0.1
did you change your url ??

**Comment by ixiDev** [comment]
Hi , No I did not change the link, please make sure you run online mode from Android Studio settings

**Comment by DjarallahBrahim** [comment]
Hi ,
I want to thank you first,
I have a question :
When i show the popup for the user and he chose yes/No  how i can use his
answer ?? Should i add something to banner/inter/.. code ??
Thank you

Le mar. 5 juin 2018 à 18:55, ABDELMAJID ID ALI <notifications@github.com> a
écrit :

**Comment by ixiDev** [comment]
Hi , yes you should use answer of user , Please read tutorial of v0.2 i
have explained that .
